"""Eliminar tabla antigua Reserva

Revision ID: 3319288bf721
Revises: 44bf449ba8d4
Create Date: 2025-07-04 07:18:58.326735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3319288bf721'
down_revision = '44bf449ba8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_estudiante', sa.VARCHAR(length=100), nullable=False),
    sa.Column('correo_estudiante', sa.VARCHAR(length=120), nullable=False),
    sa.Column('telefono_estudiante', sa.VARCHAR(length=15), nullable=False),
    sa.Column('fecha_reserva', sa.VARCHAR(length=10), nullable=False),
    sa.Column('hora_reserva', sa.VARCHAR(length=5), nullable=False),
    sa.Column('tipo_clase', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('profesor_id', sa.INTEGER(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
