"""estructura inicial con reserva_nutricionista

Revision ID: bc33aba60f93
Revises: 
Create Date: 2025-07-27 18:38:17.130245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc33aba60f93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reserva_nutricionista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('fecha_reserva', sa.String(length=10), nullable=False),
    sa.Column('hora_reserva', sa.String(length=5), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nutricionista_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['nutricionista_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservar_clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estudiante', sa.String(length=100), nullable=False),
    sa.Column('correo_estudiante', sa.String(length=120), nullable=False),
    sa.Column('telefono_estudiante', sa.String(length=15), nullable=False),
    sa.Column('fecha_reserva', sa.String(length=10), nullable=False),
    sa.Column('hora_reserva', sa.String(length=5), nullable=False),
    sa.Column('tipo_clase', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservar_clase')
    op.drop_table('reserva_nutricionista')
    op.drop_table('user')
    # ### end Alembic commands ###
